### ISSUE TITLE
the parameterlist is not consistent

### ISSUE THREAD

**Issue by a97marbr** [HGustavs/Shaker.js#5]
We use snake_case, camelCase and writtentogether ... choose one! Your call HGustavs.
``` javascript
...
shaker.hasGeoLocation = false;
shaker.geolocationcallback = null;
...
```
My vote goes to snake_case ...

**Comment by HGustavs** [comment]
My preference is camels, if I have to choose.

As the slogan says, more doctors smoke camels than any other brand.

http://tobacco.stanford.edu/tobacco_main/images_body.php?token1=fm_img0081.php

**Comment by a97marbr** [comment]
Ok. Deal.
